export default {
  completeTitle: "Complete your profile", editTitle: "Edit profile", completeDescription: "Create your personal profile before adding your first Clash account.", editDescription: "Update how you appear in the community.", displayName: "Display name *", nickname: "Clash nickname *", playerTag: "Player tag *", clanName: "Clan name", clanTag: "Clan tag", public: "Public profile", bio: "Bio", publicNotice: "Your profile and Clash accounts may be viewed by other users in the community.", save: "Save profile", saving: "Saving...", loadError: "Could not load your profile.", saveError: "Could not save the profile.", reload: "Reload profile", chooseAvatar: "Choose your avatar", avatarDescription: "Select an image to represent you in the community.", avatarOption: "Avatar {{number}}", avatarSelected: "Selected avatar", noAvatars: "No avatars available", profileAvatar: "Profile avatar", avatarOf: "{{name}}'s avatar", avatarFallback: "{{name}}'s initial", invalidAvatarFallback: "Your current avatar is no longer available. Choose a new one before saving.",
  accounts: {
    eyebrow: "Clash accounts", title: "My Clash accounts", manage: "Manage accounts", current: "Current account", used: "{{count}} of {{max}} accounts used", add: "Add account", addTitle: "Add account", editTitle: "Edit account", firstTitle: "Your first Clash account", firstDescription: "Now add the first account that will have its own collection.", formDescription: "Each account has independent details and collection.", label: "Account name/label *", avatar: "Account avatar", save: "Save account", saving: "Saving...", primary: "Main account", makePrimary: "Make primary", open: "Open collection", edit: "Edit", delete: "Delete", noClan: "No clan", progress: "progress", missing: "missing", duplicates: "duplicates", limitReached: "You have reached the free limit of 5 accounts.", deleteTitle: "Delete account", deleteDescription: "Delete {{account}}?", deleteWarning: "This account's collection will be deleted. This does not affect your profile or other accounts.", confirmDelete: "Delete account",
    errors: { load: "Could not load your accounts.", loadCollections: "Could not load the collections.", save: "Could not save the account.", delete: "Could not delete the account.", limit: "You have reached the free limit of 5 accounts.", duplicateTag: "This player tag is already linked to an account.", notFound: "Account not found or not allowed.", lastAccount: "The last Clash account cannot be deleted.", invalidOrder: "The account order is invalid." },
    validation: { label: "Enter a label with up to 40 characters.", nickname: "Enter a nickname with up to 40 characters.", clanName: "Clan name can be up to 50 characters." },
  },
  validation: { playerTagRequired: "Enter the player tag.", tagInvalid: "Use a valid tag with 5 to 14 characters after #.", displayName: "Display name must be between 2 and 40 characters.", nickname: "Nickname must be between 1 and 40 characters.", clanName: "Clan name can be up to 50 characters.", bio: "Bio can be up to 240 characters.", duplicateTag: "This player tag is already linked to another profile.", avatarRequired: "Choose a valid avatar to continue.", avatarInvalid: "The selected avatar is not available." },
};
