export default {
  completeTitle: "Complete seu perfil", editTitle: "Editar perfil", completeDescription: "Crie seu perfil pessoal antes de adicionar sua primeira conta do Clash.", editDescription: "Atualize como você aparece na comunidade.", displayName: "Nome de exibição *", nickname: "Nick no Clash *", playerTag: "Tag do jogador *", clanName: "Nome do clã", clanTag: "Tag do clã", public: "Perfil público", bio: "Bio", publicNotice: "Seu perfil e suas contas do Clash poderão ser vistos por outros usuários na comunidade.", save: "Salvar perfil", saving: "Salvando...", loadError: "Não foi possível carregar seu perfil.", saveError: "Não foi possível salvar o perfil.", reload: "Recarregar perfil", chooseAvatar: "Escolha seu avatar", avatarDescription: "Selecione uma imagem para representar você na comunidade.", avatarOption: "Avatar {{number}}", avatarSelected: "Avatar selecionado", noAvatars: "Nenhum avatar disponível", profileAvatar: "Avatar do perfil", avatarOf: "Avatar de {{name}}", avatarFallback: "Inicial de {{name}}", invalidAvatarFallback: "O avatar atual não está mais disponível. Escolha um novo para salvar.",
  accounts: {
    eyebrow: "Contas do Clash", title: "Minhas contas do Clash", manage: "Gerenciar contas", current: "Conta atual", used: "{{count}} de {{max}} contas utilizadas", add: "Adicionar conta", addTitle: "Adicionar conta", editTitle: "Editar conta", firstTitle: "Sua primeira conta do Clash", firstDescription: "Agora cadastre a primeira conta que terá sua própria coleção.", formDescription: "Cada conta possui dados e coleção independentes.", label: "Nome da conta/rótulo *", avatar: "Avatar da conta", save: "Salvar conta", saving: "Salvando...", primary: "Conta principal", makePrimary: "Tornar principal", open: "Abrir coleção", edit: "Editar", delete: "Excluir", noClan: "Sem clã", progress: "progresso", missing: "faltantes", duplicates: "repetidas", limitReached: "Você atingiu o limite gratuito de 5 contas.", deleteTitle: "Excluir conta", deleteDescription: "Excluir {{account}}?", deleteWarning: "A coleção desta conta será apagada. Esta ação não afeta seu perfil nem as outras contas.", confirmDelete: "Excluir conta",
    errors: { load: "Não foi possível carregar suas contas.", loadCollections: "Não foi possível carregar as coleções.", save: "Não foi possível salvar a conta.", delete: "Não foi possível excluir a conta.", limit: "Você atingiu o limite gratuito de 5 contas.", duplicateTag: "Esta tag de jogador já está vinculada a uma conta.", notFound: "Conta não encontrada ou sem permissão.", lastAccount: "A última conta do Clash não pode ser excluída.", invalidOrder: "A ordem das contas é inválida." },
    validation: { label: "Informe um rótulo com até 40 caracteres.", nickname: "Informe um nick com até 40 caracteres.", clanName: "O nome do clã pode ter até 50 caracteres." },
  },
  validation: { playerTagRequired: "Informe a tag do jogador.", tagInvalid: "Use uma tag válida com 5 a 14 caracteres após #.", displayName: "O nome de exibição deve ter entre 2 e 40 caracteres.", nickname: "O nick deve ter entre 1 e 40 caracteres.", clanName: "O nome do clã pode ter até 50 caracteres.", bio: "A bio pode ter até 240 caracteres.", duplicateTag: "Esta tag de jogador já está vinculada a outro perfil.", avatarRequired: "Escolha um avatar válido para continuar.", avatarInvalid: "O avatar selecionado não está disponível." },
};
