import { ArrowLeft, Copy, Swords } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { Link, useParams, useSearchParams } from "react-router-dom";
import { CardGrid } from "../components/collection/CardGrid";
import { PageContainer } from "../components/layout/PageContainer";
import { ProfileAvatar } from "../components/profile/ProfileAvatar";
import { AccountDropdown } from "../components/profile/AccountDropdown";
import { Button } from "../components/ui/Button";
import { cards } from "../data/cards";
import { categories } from "../data/categories";
import { loadCollectionsForAccounts } from "../repositories/accountCollectionRepository";
import { listPublicClashAccountsByOwner } from "../repositories/clashAccountRepository";
import { fetchPublicProfile } from "../repositories/profileRepository";
import { summarizeCollection } from "../services/collectionSummary";
import { chooseActiveClashAccount } from "../services/clashAccountState";
import { compareAllAccounts, compareCollections } from "../services/tradeComparison";
import type { AccountTradeOpportunity, ClashAccount, ClashAccountCollection } from "../types/clashAccount";
import type { CardFilter, CollectionData } from "../types/collection";
import type { PublicProfile } from "../types/profile";
import { copyToClipboard } from "../utils/clipboard";
import { cardName } from "../utils/localizedCatalog";

interface Props { myAccounts: ClashAccount[]; myActiveAccountId: string | null; myActiveCollection: CollectionData; }

export function PublicPlayerPage({ myAccounts, myActiveAccountId, myActiveCollection }: Props) {
  const { t, i18n } = useTranslation(["community", "collection"]);
  const { id = "" } = useParams();
  const [searchParams] = useSearchParams();
  const requestedMyAccountId = searchParams.get("myAccount");
  const requestedTheirAccountId = searchParams.get("theirAccount");
  const [profile, setProfile] = useState<PublicProfile | null>(null);
  const [theirAccounts, setTheirAccounts] = useState<ClashAccount[]>([]);
  const [theirCollections, setTheirCollections] = useState<Record<string, CollectionData>>({});
  const [myCollections, setMyCollections] = useState<Record<string, CollectionData>>({});
  const [theirAccountId, setTheirAccountId] = useState("");
  const [myAccountId, setMyAccountId] = useState("");
  const [mode, setMode] = useState<"all" | "specific">("all");
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [copied, setCopied] = useState(false); const [filter, setFilter] = useState<CardFilter>("all");

  useEffect(() => { let active = true; setLoading(true); setError(""); void fetchPublicProfile(id).then(async (nextProfile) => { if (!nextProfile) throw new Error(t("community:public.notFound")); const accounts = await listPublicClashAccountsByOwner(id); const collections = await loadCollectionsForAccounts(accounts); if (active) { setProfile(nextProfile); setTheirAccounts(accounts); setTheirCollections(collections); setTheirAccountId(chooseActiveClashAccount(accounts, requestedTheirAccountId)?.id ?? ""); if (requestedMyAccountId || requestedTheirAccountId) setMode("specific"); } }).catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : t("community:public.loadError")); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [id, requestedMyAccountId, requestedTheirAccountId, t]);
  useEffect(() => { let active = true; if (!myAccounts.length) return; void loadCollectionsForAccounts(myAccounts).then((collections) => { if (!active) return; setMyCollections(myActiveAccountId ? { ...collections, [myActiveAccountId]: myActiveCollection } : collections); setMyAccountId((current) => { const currentIsValid = myAccounts.some((account) => account.id === current); const preferredId = requestedMyAccountId ?? (currentIsValid ? current : myActiveAccountId); return chooseActiveClashAccount(myAccounts, preferredId)?.id ?? ""; }); }).catch(() => undefined); return () => { active = false; }; }, [myAccounts, myActiveAccountId, myActiveCollection, requestedMyAccountId]);

  const mine = useMemo(() => asAccountCollections(myAccounts, myCollections), [myAccounts, myCollections]);
  const theirs = useMemo(() => asAccountCollections(theirAccounts, theirCollections), [theirAccounts, theirCollections]);
  const allComparison = useMemo(() => compareAllAccounts(mine, theirs), [mine, theirs]);
  const selectedMine = mine.find((item) => item.account.id === myAccountId) ?? mine[0];
  const selectedTheirs = theirs.find((item) => item.account.id === theirAccountId) ?? theirs[0];
  const specificComparison = useMemo(() => selectedMine && selectedTheirs ? compareCollections(cards, selectedMine.collection, selectedTheirs.collection) : null, [selectedMine, selectedTheirs]);

  if (loading) return <PageContainer><div className="pt-8 text-stone-400">{t("community:public.loading")}</div></PageContainer>;
  if (error || !profile) return <PageContainer><div className="pt-8"><Link className="text-amber-300" to="/comunidade">← {t("community:public.back")}</Link><p className="mt-8 rounded-2xl bg-red-500/10 p-5 text-red-200">{error}</p></div></PageContainer>;
  const selectedAccount = selectedTheirs?.account ?? null;
  const collection = selectedTheirs?.collection ?? emptyCollection(profile.displayName);
  const visibleCards = cards.filter((card) => { const state = collection.cards[card.id]; if (filter === "owned") return state?.owned; if (filter === "missing") return !state?.owned; if (filter === "duplicates") return (state?.duplicates ?? 0) > 0; return true; });
  const proposal = buildProposal(profile, mode, selectedMine, selectedTheirs, allComparison.theirsForMe, allComparison.mineForThem, mine, theirs, t);

  return <PageContainer><div className="space-y-6 pt-6">
    <Link className="inline-flex items-center gap-2 text-sm font-black text-stone-400 hover:text-white" to="/comunidade"><ArrowLeft size={16} /> {t("community:public.back")}</Link>
    <section className="panel-metal rounded-3xl p-5 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-start"><ProfileAvatar avatarUrl={profile.avatarUrl} displayName={profile.displayName} size="xl" /><div className="min-w-0 flex-1"><p className="text-xs font-black uppercase tracking-wider text-amber-400">{t("community:public.eyebrow")}</p><h2 className="mt-1 break-words font-display text-3xl text-white">{profile.displayName}</h2><p className="mt-2 text-sm font-bold text-amber-300/80">{t("community:accountCount", { count: theirAccounts.length })}</p>{profile.bio && <p className="mt-4 max-w-2xl whitespace-pre-line break-words text-sm leading-relaxed text-stone-400">{profile.bio}</p>}</div></div></section>
    {theirAccounts.length > 0 && <section className="panel-metal rounded-3xl p-4 sm:p-5"><div className="flex gap-2 overflow-x-auto pb-1">{theirAccounts.map((account) => <button key={account.id} className={`shrink-0 rounded-xl px-3 py-2 text-xs font-black ${account.id === theirAccountId ? "bg-amber-300 text-stone-950" : "bg-white/5 text-stone-300"}`} onClick={() => setTheirAccountId(account.id)}>{account.accountLabel}</button>)}</div>{selectedAccount && <div className="mt-4 flex min-w-0 items-start gap-3"><ProfileAvatar avatarUrl={selectedAccount.avatarUrl} displayName={selectedAccount.clashNickname} size="md" /><div className="min-w-0"><h3 className="truncate font-black text-white">{selectedAccount.clashNickname} · {selectedAccount.clashPlayerTag}</h3><p className="truncate text-sm text-stone-500">{selectedAccount.clanName || t("community:public.noClan")}{selectedAccount.clanTag ? ` · ${selectedAccount.clanTag}` : ""}</p><p className="mt-2 text-xs text-stone-500">{t("community:public.lastUpdate", { date: collection.updatedAt ? new Date(collection.updatedAt).toLocaleString(i18n.language) : t("community:public.noDate") })}</p><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="secondary" onClick={() => void copyToClipboard(selectedAccount.clashPlayerTag)}><Copy size={14} /> {t("community:public.copyPlayerTag")}</Button>{selectedAccount.clanTag && <Button size="sm" variant="secondary" onClick={() => void copyToClipboard(selectedAccount.clanTag!)}><Copy size={14} /> {t("community:public.copyClanTag")}</Button>}</div></div></div>}</section>}
    <section className="panel-wood min-w-0 rounded-3xl p-5"><div className="min-w-0"><p className="flex items-center gap-2 text-xs font-black uppercase text-amber-300"><Swords size={16} /> {t("community:public.compatibility")}</p><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant={mode === "all" ? "primary" : "secondary"} onClick={() => setMode("all")}>{t("community:public.compareAll")}</Button><Button size="sm" variant={mode === "specific" ? "primary" : "secondary"} onClick={() => setMode("specific")}>{t("community:public.compareSpecific")}</Button></div>{mode === "specific" ? <div className="mt-3 grid min-w-0 gap-3 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]"><AccountSelect label={t("community:public.myAccount")} value={myAccountId} accounts={myAccounts} onChange={setMyAccountId} testId="public-my-account-dropdown" /><AccountSelect label={t("community:public.theirAccount")} value={theirAccountId} accounts={theirAccounts} onChange={setTheirAccountId} testId="public-their-account-dropdown" /><TradeList title={t("community:public.offerRoute", { source: selectedTheirs?.account.accountLabel ?? profile.displayName, target: selectedMine?.account.accountLabel ?? t("community:public.myAccount") })} items={(specificComparison?.theirsForMe ?? []).map((card) => `${cardName(card)} x${selectedTheirs?.collection.cards[card.id]?.duplicates ?? 0}`)} /><TradeList title={t("community:public.offerRoute", { source: selectedMine?.account.accountLabel ?? t("community:public.myAccount"), target: selectedTheirs?.account.accountLabel ?? profile.displayName })} items={(specificComparison?.mineForThem ?? []).map((card) => `${cardName(card)} x${selectedMine?.collection.cards[card.id]?.duplicates ?? 0}`)} /></div> : <OpportunityGroups opportunities={[...allComparison.theirsForMe, ...allComparison.mineForThem]} allAccounts={[...mine, ...theirs]} />}</div><div className="mt-4 flex justify-end"><Button className="max-w-full" disabled={!proposal} onClick={() => void copyToClipboard(proposal).then(() => { setCopied(true); window.setTimeout(() => setCopied(false), 1800); })}><Copy size={16} /> {copied ? t("community:public.copied") : t("community:public.copyProposal")}</Button></div></section>
    <section><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h3 className="font-display text-2xl text-white">{t("community:public.collectionOf", { name: selectedAccount?.accountLabel ?? profile.displayName })}</h3><select className="field h-10 py-1 text-sm" value={filter} onChange={(event) => setFilter(event.target.value as CardFilter)} aria-label={t("community:public.filter")}><option value="all">{t("collection:filters.all")}</option><option value="owned">{t("collection:filters.owned")}</option><option value="missing">{t("collection:filters.missing")}</option><option value="duplicates">{t("collection:filters.duplicates")}</option></select></div>{categories.map((category) => { const group = visibleCards.filter((card) => card.category === category.id); return group.length ? <div className="mb-7" key={category.id}><h4 className="mb-3 text-xs font-black uppercase tracking-[.16em] text-stone-400">{t(`collection:${category.nameKey}`)}</h4><CardGrid cards={group} getState={(cardId) => collection.cards[cardId] ?? { owned: false, duplicates: 0 }} onToggle={() => undefined} onDuplicatesChange={() => undefined} readOnly /></div> : null; })}</section>
  </div></PageContainer>;
}

function asAccountCollections(accounts: ClashAccount[], collections: Record<string, CollectionData>): ClashAccountCollection[] { return accounts.map((account) => { const collection = collections[account.id] ?? emptyCollection(account.clashNickname); return { account, collection, summary: summarizeCollection(collection) }; }); }
function emptyCollection(playerName: string): CollectionData { return { version: 2, playerName, updatedAt: null, cards: {}, preferences: { category: "all", filter: "all" } }; }
function AccountSelect({ label, value, accounts, onChange, testId }: { label: string; value: string; accounts: ClashAccount[]; onChange: (value: string) => void; testId: string }) { return <div className="min-w-0"><span className="mb-1 block text-[10px] font-black uppercase text-stone-500">{label}</span><AccountDropdown accounts={accounts} value={value} onChange={onChange} ariaLabel={label} testId={testId} /></div>; }
function TradeList({ title, items }: { title: string; items: string[] }) { const { t } = useTranslation("community"); return <div className="rounded-2xl bg-black/20 p-3"><h3 className="text-xs font-black text-stone-300">{title}</h3>{items.length ? <ul className="mt-2 space-y-1 text-sm text-stone-400">{items.map((item) => <li key={item}>• {item}</li>)}</ul> : <p className="mt-2 text-xs text-stone-600">{t("public.none")}</p>}</div>; }
function OpportunityGroups({ opportunities, allAccounts }: { opportunities: AccountTradeOpportunity[]; allAccounts: ClashAccountCollection[] }) { const { t } = useTranslation("community"); const accounts = new Map(allAccounts.map((item) => [item.account.id, item])); const grouped = new Map<string, AccountTradeOpportunity[]>(); opportunities.forEach((item) => { const key = `${item.sourceAccountId}:${item.targetAccountId}`; grouped.set(key, [...(grouped.get(key) ?? []), item]); }); if (!opportunities.length) return <p className="mt-3 text-sm text-stone-500">{t("public.none")}</p>; return <div className="mt-3 grid gap-3 md:grid-cols-2">{[...grouped.entries()].map(([key, items]) => { const source = accounts.get(items[0].sourceAccountId); const target = accounts.get(items[0].targetAccountId); return <div key={key} className="rounded-2xl bg-black/20 p-3"><h3 className="text-xs font-black text-stone-300">{source?.account.accountLabel} → {target?.account.accountLabel}</h3><ul className="mt-2 space-y-1 text-sm text-stone-400">{items.map((item) => <li key={`${item.cardId}:${item.sourceAccountId}:${item.targetAccountId}`}>• {cardName(cards.find((card) => card.id === item.cardId)!)} x{source?.collection.cards[item.cardId]?.duplicates ?? 0}</li>)}</ul></div>; })}</div>; }
function buildProposal(profile: PublicProfile, mode: "all" | "specific", mine: ClashAccountCollection | undefined, theirs: ClashAccountCollection | undefined, theirsForMe: AccountTradeOpportunity[], mineForThem: AccountTradeOpportunity[], allMine: ClashAccountCollection[], allTheirs: ClashAccountCollection[], t: ReturnType<typeof useTranslation>["t"]): string { if (mode === "specific") { if (!mine || !theirs) return ""; const comparison = compareCollections(cards, mine.collection, theirs.collection); const lines = [t("community:public.proposalGreeting", { name: profile.displayName }), `${mine.account.accountLabel} (${mine.account.clashNickname}) × ${theirs.account.accountLabel} (${theirs.account.clashNickname})`]; if (comparison.theirsForMe.length) lines.push("", t("community:public.receiving"), ...comparison.theirsForMe.map((card) => `- ${cardName(card)} x${theirs.collection.cards[card.id]?.duplicates ?? 0}`)); if (comparison.mineForThem.length) lines.push("", t("community:public.offering"), ...comparison.mineForThem.map((card) => `- ${cardName(card)} x${mine.collection.cards[card.id]?.duplicates ?? 0}`)); return lines.join("\n"); } const accounts = new Map([...allMine, ...allTheirs].map((item) => [item.account.id, item])); const lines = [t("community:public.proposalGreeting", { name: profile.displayName })]; [...theirsForMe, ...mineForThem].forEach((item) => { const source = accounts.get(item.sourceAccountId); const target = accounts.get(item.targetAccountId); const card = cards.find((candidate) => candidate.id === item.cardId); if (source && target && card) lines.push(`${source.account.accountLabel} → ${target.account.accountLabel}: ${cardName(card)} x${source.collection.cards[item.cardId]?.duplicates ?? 0}`); }); return lines.length > 1 ? lines.join("\n") : ""; }
